arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - base_link_to_main_mast
    - main_mast_to_second_stage
  gains:
    base_link_to_main_mast:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    main_mast_to_second_stage:
      p: 100
      d: 1
      i: 1
      i_clamp: 1