generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

hardware_interface:
   joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
   sim_control_mode: 0 # 0: position, 1: velocity

joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 50

# Joint Trajectory Controller -------------------------------
# For detailed explanations of parameter see http://wiki.ros.org/joint_trajectory_controller
position_trajectory_controller:
   type: position_controllers/JointTrajectoryController
   # These joints can likely just be copied from the hardware_interface list above
   joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
   constraints:
      goal_time: 5.0
      #stopped_position_tolerance: 0.4 # Defaults to 0.01
      joint_1:
          trajectory: 0.60
          goal:       0.15
      joint_2:
          trajectory: 0.60
          goal:       0.15
      joint_3:
          trajectory: 0.60
          goal:       0.15
      joint_4:
          trajectory: 0.60
          goal:       0.15
      joint_5:
          trajectory: 0.60
          goal:       0.15
      joint_6:
          trajectory: 0.60
          goal:       0.15